export default {
  meta: { name: "architecture", storageKey: "arch-diagram-positions", height: 800 },
  zones: [
    { id: "zone-client", type: "zone", position: { x: 0, y: 0 }, data: { label: "Client Layer", color: "#34d399", width: 680, height: 90 } },
    { id: "zone-backend", type: "zone", position: { x: 0, y: 110 }, data: { label: "Your Marketplace Backend", color: "#a78bfa", width: 500, height: 380 } },
    { id: "zone-topsort", type: "zone", position: { x: 520, y: 110 }, data: { label: "Topsort (External)", color: "#4f8ff7", width: 350, height: 380 } },
    { id: "zone-data", type: "zone", position: { x: 0, y: 510 }, data: { label: "Data Layer", color: "#fbbf24", width: 500, height: 110 } },
    { id: "zone-ts-internal", type: "zone", position: { x: 520, y: 510 }, data: { label: "Topsort Internal", color: "#4f8ff7", width: 350, height: 110 } },
    { id: "zone-reporting", type: "zone", position: { x: 0, y: 640 }, data: { label: "Your Reporting", color: "#a78bfa", width: 500, height: 90 } },
    { id: "zone-ts-outputs", type: "zone", position: { x: 520, y: 640 }, data: { label: "Topsort Outputs", color: "#4f8ff7", width: 350, height: 90 } },
  ],
  nodes: [
    { id: "user", type: "service", position: { x: 30, y: 20 }, data: { label: "User", subtitle: "Browser / App", borderColor: "#34d399", flows: ["search","catalog","events","purchase"] } },
    { id: "frontend", type: "service", position: { x: 200, y: 20 }, data: { label: "Frontend", subtitle: "React / Next.js", borderColor: "#34d399", flows: ["search","events","purchase"] } },
    { id: "jssdk", type: "external", position: { x: 400, y: 20 }, data: { label: "Topsort JS SDK", subtitle: "analytics.js", dashed: true, flows: ["events"] } },
    { id: "apigw", type: "service", position: { x: 200, y: 140 }, data: { label: "API Gateway", subtitle: "OAuth / Rate Limit", borderColor: "#a78bfa", flows: ["search","purchase"] } },
    { id: "search", type: "service", position: { x: 30, y: 240 }, data: { label: "Search Service", subtitle: "Organic + Merge", borderColor: "#a78bfa", flows: ["search"] } },
    { id: "tsclient", type: "service", position: { x: 220, y: 240 }, data: { label: "Topsort Client", subtitle: "100ms timeout / CB", borderColor: "#4f8ff7", flows: ["search"] } },
    { id: "order", type: "service", position: { x: 370, y: 240 }, data: { label: "Order Service", subtitle: "Checkout", borderColor: "#a78bfa", flows: ["purchase"] } },
    { id: "catalog-svc", type: "service", position: { x: 30, y: 330 }, data: { label: "Catalog Service", subtitle: "EXISTING \u2014 product CRUD", borderColor: "#34d399", flows: ["catalog"] } },
    { id: "event-relay", type: "service", position: { x: 370, y: 330 }, data: { label: "Event Relay", subtitle: "Batch / Retry / DLQ", borderColor: "#fbbf24", flows: ["events","purchase"] } },
    { id: "catalog-sync", type: "service", position: { x: 30, y: 420 }, data: { label: "Catalog Sync", badge: "NEW \u2014 for Topsort", subtitle: "transform + batch", borderColor: "#22d3ee", flows: ["catalog"] } },
    { id: "ts-apigw", type: "external", position: { x: 560, y: 140 }, data: { label: "Topsort API GW", subtitle: "Auth / Routing", flows: ["search","catalog","events","purchase"] } },
    { id: "auctions-api", type: "external", position: { x: 560, y: 240 }, data: { label: "Auctions API", subtitle: "POST /v2/auctions", flows: ["search"] } },
    { id: "catalog-api", type: "external", position: { x: 730, y: 240 }, data: { label: "Catalog API", subtitle: "PUT /public/v1/...", borderColor: "#34d399", flows: ["catalog"] } },
    { id: "events-api", type: "external", position: { x: 560, y: 340 }, data: { label: "Events API", subtitle: "POST /v2/events", borderColor: "#fbbf24", flows: ["events","purchase"] } },
    { id: "postgres", type: "datastore", position: { x: 20, y: 540 }, data: { label: "PostgreSQL", subtitle: "Products/Orders", flows: ["search","catalog","purchase"] } },
    { id: "es", type: "datastore", position: { x: 150, y: 540 }, data: { label: "Elasticsearch", subtitle: "Search Index", flows: ["search"] } },
    { id: "redis", type: "datastore", position: { x: 280, y: 540 }, data: { label: "Redis", subtitle: "Cache", flows: ["search"] } },
    { id: "kafka", type: "datastore", position: { x: 400, y: 540 }, data: { label: "Kafka", subtitle: "Event Bus", flows: ["catalog"] } },
    { id: "auction-engine", type: "external", position: { x: 540, y: 535 }, data: { label: "Auction Engine", subtitle: "eCPM / 2nd Price", borderColor: "#1a3060", flows: ["search"] } },
    { id: "attribution", type: "external", position: { x: 710, y: 535 }, data: { label: "Attribution", subtitle: "Click/View-thru", borderColor: "#1a3060", flows: ["events","purchase"] } },
    { id: "billing", type: "external", position: { x: 540, y: 585 }, data: { label: "Billing", subtitle: "CPC / CPM / CPA", borderColor: "#1a3060", flows: ["purchase"] } },
    { id: "product-index", type: "external", position: { x: 710, y: 585 }, data: { label: "Product Index", subtitle: "Topsort's catalog", borderColor: "#1a3060", flows: ["catalog"] } },
    { id: "admin-dash", type: "service", position: { x: 30, y: 665 }, data: { label: "Admin Dashboard", subtitle: "Revenue / Performance", borderColor: "#a78bfa", flows: ["purchase"] } },
    { id: "reporting-api", type: "external", position: { x: 560, y: 660 }, data: { label: "Reporting API", subtitle: "GET /v2/reports", flows: ["purchase"] } },
    { id: "toppie", type: "external", position: { x: 730, y: 660 }, data: { label: "Toppie (DSP)", subtitle: "Advertiser Portal" } },
  ],
  edges: [
    { id: "e-user-frontend", source: "user", target: "frontend", sourceHandle: "right", targetHandle: "left", data: { label: "1", color: "#4f8ff7", flows: ["search"] } },
    { id: "e-frontend-apigw", source: "frontend", target: "apigw", data: { label: "2", color: "#4f8ff7", flows: ["search"] } },
    { id: "e-apigw-search", source: "apigw", target: "search", data: { label: "3a route", color: "#4f8ff7", flows: ["search"] } },
    { id: "e-search-tsclient", source: "search", target: "tsclient", sourceHandle: "right", targetHandle: "left", data: { label: "3b parallel", color: "#4f8ff7", flows: ["search"] } },
    { id: "e-tsclient-tsapigw", source: "tsclient", target: "ts-apigw", sourceHandle: "right", targetHandle: "left", data: { label: "4 POST /v2/auctions", color: "#4f8ff7", flows: ["search"] } },
    { id: "e-tsapigw-tsclient", source: "ts-apigw", target: "tsclient", sourceHandle: "left", targetHandle: "right", data: { label: "5 winners[]", color: "#4f8ff7", dashed: true, flows: ["search"] } },
    { id: "e-search-es", source: "search", target: "es", data: { label: "3c ES query", color: "#4f8ff7", flows: ["search"] } },
    { id: "e-search-frontend", source: "search", target: "frontend", data: { label: "6 merged", color: "#4f8ff7", dashed: true, flows: ["search"] } },
    { id: "e-cat-pg", source: "catalog-svc", target: "postgres", data: { label: "A write", color: "#34d399", flows: ["catalog"] } },
    { id: "e-cat-kafka", source: "catalog-svc", target: "kafka", sourceHandle: "right", targetHandle: "left", data: { label: "B publish product.updated", color: "#34d399", dashed: true, flows: ["catalog"] } },
    { id: "e-kafka-sync", source: "kafka", target: "catalog-sync", targetHandle: "right", sourceHandle: "left", data: { label: "C consume", color: "#22d3ee", flows: ["catalog"] } },
    { id: "e-sync-catapi", source: "catalog-sync", target: "catalog-api", sourceHandle: "right", targetHandle: "left", data: { label: "D PUT /public/v1/.../products", color: "#22d3ee", flows: ["catalog"] } },
    { id: "e-frontend-jssdk", source: "frontend", target: "jssdk", sourceHandle: "right", targetHandle: "left", data: { label: "resolvedBidId", color: "#fbbf24", flows: ["events"] } },
    { id: "e-jssdk-eventsapi", source: "jssdk", target: "events-api", data: { label: "Client: POST /v2/events", color: "#fbbf24", flows: ["events"] } },
    { id: "e-relay-eventsapi", source: "event-relay", target: "events-api", sourceHandle: "right", targetHandle: "left", data: { label: "Server: POST /v2/events", color: "#fbbf24", flows: ["events","purchase"] } },
    { id: "e-frontend-apigw-purchase", source: "frontend", target: "apigw", data: { label: "POST /checkout", color: "#fb7185", flows: ["purchase"] } },
    { id: "e-apigw-order", source: "apigw", target: "order", sourceHandle: "right", targetHandle: "left", data: { label: "route", color: "#fb7185", flows: ["purchase"] } },
    { id: "e-order-relay", source: "order", target: "event-relay", data: { label: "purchase event", color: "#fb7185", flows: ["purchase"] } },
    { id: "e-order-pg", source: "order", target: "postgres", data: { label: "write order", color: "#fb7185", flows: ["purchase"] } },
    { id: "e-eventsapi-attr", source: "events-api", target: "attribution", data: { label: "match", color: "#fb7185", flows: ["purchase"] } },
    { id: "e-attr-billing", source: "attribution", target: "billing", sourceHandle: "left", targetHandle: "right", data: { label: "charge", color: "#fb7185", flows: ["purchase"] } },
    { id: "e-reportapi-dash", source: "reporting-api", target: "admin-dash", sourceHandle: "left", targetHandle: "right", data: { label: "GET /v2/reports (periodic)", color: "#a78bfa", dashed: true, flows: ["purchase"] } },
  ],
  flowDescriptions: {
    all: "All Flows: Complete architecture showing every component. Click a specific flow to isolate a request path.",
    search: "Search + Auction: User searches \u2192 Frontend \u2192 API GW \u2192 Search Service (parallel: Topsort Client + ES query) \u2192 POST /v2/auctions \u2192 winners[] returned \u2192 merged results.",
    catalog: "Catalog Sync: Catalog Service (existing) writes to PostgreSQL and publishes product.updated to Kafka. Catalog Sync (new) consumes, transforms, and PUTs to Topsort Catalog API.",
    events: "Events: Client path: Frontend passes resolvedBidId to JS SDK \u2192 SDK fires POST /v2/events directly. Server path: Event Relay batches and sends.",
    purchase: "Purchase: POST /checkout \u2192 Order Service \u2192 purchase event \u2192 Event Relay \u2192 Events API \u2192 Attribution \u2192 Billing \u2192 Reports to dashboard.",
  },
  flowLabels: {
    all: "Show All",
    search: "Search + Auction",
    catalog: "Catalog Sync",
    events: "Impressions & Clicks",
    purchase: "Purchase & Attribution",
  },
  legend: [
    { color: "#4f8ff7", label: "Search + Auction", dashed: false },
    { color: "#34d399", label: "Catalog Service (existing)", dashed: false },
    { color: "#22d3ee", label: "Catalog Sync (new)", dashed: false },
    { color: "#fbbf24", label: "Event Tracking", dashed: false },
    { color: "#fb7185", label: "Purchase + Attribution", dashed: false },
    { color: "#6a7090", label: "Response path", dashed: true },
  ],
}
