export default {
  meta: { name: "overview", storageKey: "overview-diagram-positions", height: 600 },
  zones: [
    { id: "zone-mkt", type: "zone", position: { x: -15, y: -15 }, data: { label: "Your Marketplace", color: "#34d399", width: 360, height: 400 } },
    { id: "zone-infra", type: "zone", position: { x: 355, y: -15 }, data: { label: "Infrastructure", color: "#fbbf24", width: 170, height: 365 } },
    { id: "zone-ts", type: "zone", position: { x: 535, y: -15 }, data: { label: "Topsort", color: "#4f8ff7", width: 340, height: 400 } },
  ],
  nodes: [
    { id: "frontend", type: "service", position: { x: 10, y: 15 }, data: { label: "Frontend", subtitle: "React / Next.js", borderColor: "#34d399" } },
    { id: "apigw", type: "service", position: { x: 10, y: 95 }, data: { label: "API Gateway", subtitle: "Auth / Rate Limit", borderColor: "#34d399" } },
    { id: "search-svc", type: "service", position: { x: 10, y: 175 }, data: { label: "Search Service", subtitle: "Organic + Merge", borderColor: "#34d399" } },
    { id: "ts-client", type: "service", position: { x: 190, y: 175 }, data: { label: "Topsort Client", subtitle: "Circuit Breaker", borderColor: "#34d399" } },
    { id: "catalog-svc", type: "service", position: { x: 10, y: 255 }, data: { label: "Catalog Service", badge: "EXISTING", borderColor: "#34d399" } },
    { id: "event-relay", type: "service", position: { x: 190, y: 255 }, data: { label: "Event Relay", subtitle: "Batch + Retry", borderColor: "#34d399" } },
    { id: "catalog-sync", type: "service", position: { x: 10, y: 345 }, data: { label: "Catalog Sync", badge: "NEW", borderColor: "#22d3ee" } },
    { id: "es", type: "datastore", position: { x: 370, y: 110 }, data: { label: "ES", subtitle: "Search Index" } },
    { id: "postgres", type: "datastore", position: { x: 370, y: 190 }, data: { label: "PostgreSQL", subtitle: "Products/Orders" } },
    { id: "kafka", type: "datastore", position: { x: 370, y: 300 }, data: { label: "Kafka", subtitle: "Event Bus" } },
    { id: "auctions-api", type: "external", position: { x: 560, y: 60 }, data: { label: "Auctions API", subtitle: "POST /v2/auctions" } },
    { id: "events-api", type: "external", position: { x: 560, y: 160 }, data: { label: "Events API", subtitle: "POST /v2/events" } },
    { id: "catalog-api", type: "external", position: { x: 560, y: 340 }, data: { label: "Catalog API", subtitle: "PUT /public/v1/...", borderColor: "#34d399" } },
    { id: "auction-engine", type: "external", position: { x: 720, y: 100 }, data: { label: "Auction Engine", subtitle: "eCPM Ranking", borderColor: "#1a3060" } },
    { id: "attribution", type: "external", position: { x: 720, y: 200 }, data: { label: "Attribution", subtitle: "Click/View-thru", borderColor: "#1a3060" } },
    { id: "billing", type: "external", position: { x: 720, y: 295 }, data: { label: "Billing", subtitle: "CPC / CPM / CPA", borderColor: "#1a3060" } },
  ],
  edges: [
    { id: "e-fe-apigw", source: "frontend", target: "apigw", data: { color: "#5c6178" } },
    { id: "e-apigw-search", source: "apigw", target: "search-svc", data: { color: "#5c6178" } },
    { id: "e-search-tsclient", source: "search-svc", target: "ts-client", sourceHandle: "right", targetHandle: "left", data: { label: "parallel", color: "#4f8ff7" } },
    { id: "e-cat-pg", source: "catalog-svc", target: "postgres", sourceHandle: "right", targetHandle: "left", data: { label: "write", color: "#5c6178" } },
    { id: "e-cat-kafka", source: "catalog-svc", target: "kafka", sourceHandle: "right", targetHandle: "left", data: { label: "publish", color: "#fbbf24", dashed: true } },
    { id: "e-kafka-sync", source: "kafka", target: "catalog-sync", sourceHandle: "left", targetHandle: "right", data: { label: "consume", color: "#22d3ee", dashed: true } },
    { id: "e-tsclient-auctions", source: "ts-client", target: "auctions-api", sourceHandle: "right", targetHandle: "left", data: { label: "Auctions", color: "#4f8ff7" } },
    { id: "e-relay-events", source: "event-relay", target: "events-api", sourceHandle: "right", targetHandle: "left", data: { label: "Events", color: "#fbbf24" } },
    { id: "e-sync-catalog", source: "catalog-sync", target: "catalog-api", sourceHandle: "right", targetHandle: "left", data: { label: "Catalog Sync", color: "#34d399" } },
    { id: "e-auctions-engine", source: "auctions-api", target: "auction-engine", sourceHandle: "right", targetHandle: "left", data: { color: "#4f8ff7", dashed: true } },
    { id: "e-events-attr", source: "events-api", target: "attribution", sourceHandle: "right", targetHandle: "left", data: { color: "#fbbf24", dashed: true } },
    { id: "e-attr-billing", source: "attribution", target: "billing", data: { color: "#fb7185", dashed: true } },
  ],
}
